### ISSUE TITLE
A few issues with the Jan 16 assignment

### ISSUE THREAD

**Issue by natenolting** [mschumacher1/BUAD-3283#2]
https://github.com/mschumacher1/BUAD-3283/blob/57e3c934e7db58978d48b558c95ce53200326222/Code%20assignment%201.txt#L1

You have most of the elements correct, the file just needs to be moved and updated.

See https://github.com/natenolting/BUAD-3283-E-Commerce-Web-Development/blob/spring2018/course_assignment/course_assignment_03_January_16.md

- [ ] "Create a folder in your repository **assignments/January_16** with the file **index.html** in it." So rename this file and move it to the right directory.
- [ ] [#1 Write the DOCTYPE, head and body tags to your index.html](https://github.com/mschumacher1/BUAD-3283/blob/57e3c934e7db58978d48b558c95ce53200326222/Code%20assignment%201.txt#L1)
- [ ] [#5 Write a paragraph with 4 sentences to you index.html](https://github.com/mschumacher1/BUAD-3283/blob/57e3c934e7db58978d48b558c95ce53200326222/Code%20assignment%201.txt#L11-L14). You need to wrap these lines with a paragraph`<p>` tag.
- [ ] [#6 Make an unordered list of the color wheel primary colors](https://github.com/mschumacher1/BUAD-3283/blob/57e3c934e7db58978d48b558c95ce53200326222/Code%20assignment%201.txt#L16-L20). The syntax for the `li`s should be like `<li style="color:red;">red</li>` if you wanted those items styled. 
- [ ] [#9 Create a paragraph that contains some links.](https://github.com/mschumacher1/BUAD-3283/blob/57e3c934e7db58978d48b558c95ce53200326222/Code%20assignment%201.txt#L51-L53) 
    - This block is missing the wrapping paragraph `<p>` tag. 
    - Your email link should start with a `mailto:`
    - You need an anchor link.

Also it kind of looks like you started adding your January 25th assignment to this file. They should be in separate files and in separate folders.

See https://github.com/natenolting/BUAD-3283-E-Commerce-Web-Development/blob/spring2018/course_notes/course_notes_03_January_16.md and https://github.com/natenolting/BUAD-3283-E-Commerce-Web-Development/blob/spring2018/course_notes/course_notes_04_January_18.md for help. If you're still really stuck ask me after class on 2-6.
